### ISSUE TITLE
Document: Install nvm, NodeJs and yarn

### ISSUE THREAD

**Issue by popelenkow** [popelenkow/peredelano-profile#1]
Install nvm https://github.com/coreybutler/nvm-windows/releases for Windows
Install nvm https://github.com/nvm-sh/nvm#installing-and-updating for Linux and MacOS

Install Node JS `nvm install 18.16.0`

Original NodeJs website https://nodejs.org/en

Install yarn https://classic.yarnpkg.com/lang/en/docs/install/#windows-stable

**Comment by Olnipa** [comment]
Done
